///////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2017 Bjorn Reese <breese@users.sourceforge.net>
//
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
//
///////////////////////////////////////////////////////////////////////////////

== Design Rationale

This section describes the principles behind the design of `dynamic::variable`.

=== Supported Types

`dynamic::variable` only supports a pre-defined list of types. No custom types
are allowed. This restriction is imposed to define various relationships between
supported types such that `dynamic::variable` can meet the requirements for the
Container concept.

The `dynamic::nullable` type indicates that the variable contains no value.
It serves the same purpose as `std::nullopt_t`.

// Arithmetic

// The many strings (locale not mandated, thus no implicit conversion between them)

The `dynamic::array` type adheres to the `SequenceContainer` concept.

The `dynamic::map` type adheres to the `AssociativeContainer` concept with a `mapped_type`.
 
A variable can only change its type via construction, assignment, or swapping.
For instance, the `clear()` member function resets the content of a variable,
but retains the type. Assigning an unsupported type to a variable results in a
compile-time error.

//* Operations with incompatible supported types are detected at run-time.

//Emulates operations of underlying types where possible, except:
//  1. Comparison (see below)
//  2. Throws exceptions instead of generating compiler errors for some operations.

// is<boolean>() versus is_boolean(): meta-programming
// pre-condition: assert(is<T>());

// Implicit versus explicit conversion

=== Container Concept

`dynamic::variable` adheres to the Container concept.

When container operations are performed on a variable, then a nullable value is
considered an array of size 0, a boolean, integer, floating-point, or string
value is considered an array of size 1, and array and map are containers whose
size is the number of contained elements.

=== Comparison

// http://en.cppreference.com/w/cpp/utility/optional/operator_cmp
// http://en.cppreference.com/w/cpp/utility/variant/operator_cmp

The null value has a special meaning in comparisons.

The rules for comparisons follows those of http://en.cppreference.com/w/cpp/utility/optional[`std::optional`],
albeit with a few deviations.

* `dynamic::null` only equals `dynamic::null`, and is less than any other type.
* Comparison between arithmetic types follows C++ rules, with the
  exception of comparison between signed and unsigned integers.
* Comparison between unrelated supported types use this relationship:
  null > arithmetic > string > wstring > u16string > u32string > array > map

//Comparison

//Comparison: Works similar to std::nullopt:
//  1. variable::null only equals variable::null.
//  2. variable::null is smaller than objects of other types.

//signed/unsigned: no warning (do not know how to enable)
//scalar vs string: works to make std::adjacent_find() work
//  null > arithmetic > string > array > map

=== Traversal

// key_iterator
//   std::pair
//   const

// Visitor

=== Customization

`dynamic::variable` is an alias for `dynamic::basic_variable<std::allocator>`.

`dynamic::basic_variable` can be customized with an allocator. The allocator is
passed to all its string types, as well as `array_type` and `map_type`.
