:space: &#160;&#160;&#160;&#160;&#160;

[[dynamic_variable]]
=== Header <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>

[source,cpp]
----
namespace trial {
  namespace dynamic {
    template<template< typename > class Allocator> struct basic_array;
    template<template< typename > class Allocator> struct basic_map;

    template<template< typename > class Allocator> class basic_variable;

    struct boolean;
    struct integer;
    struct real;
    struct string;
    struct u16string;
    struct u32string;
    struct wstring;

    enum nullable { null };

    typedef basic_variable< std::allocator > variable;
    typedef basic_array< std::allocator > array;
    typedef basic_map< std::allocator > map;
    template<template< typename > class Allocator, typename U> 
      basic_variable< Allocator > 
      operator+(const basic_variable< Allocator > &, const U &);
    template<template< typename > class Allocator> 
      basic_variable< Allocator > 
      operator+(nullable, const basic_variable< Allocator > &);
    template<typename T, typename U> bool operator==(const T &, const U &);
    template<typename T, typename U> bool operator!=(const T &, const U &);
    template<typename T, typename U> bool operator<(const T &, const U &);
    template<template< typename > class Allocator, typename U> 
      bool operator<=(const basic_variable< Allocator > &, const U &);
    template<template< typename > class Allocator, typename U> 
      bool operator>(const basic_variable< Allocator > &, const U &);
    template<template< typename > class Allocator, typename U> 
      bool operator>=(const basic_variable< Allocator > &, const U &);
  }
}
----

== Struct template basic_array

trial::dynamic::basic_array

=== Synopsis

[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>

template<template< typename > class Allocator> 
struct basic_array {
};
----

== Struct template basic_map

trial::dynamic::basic_map

=== Synopsis

[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>

template<template< typename > class Allocator> 
struct basic_map {
};
----


== Class template basic_variable


trial::dynamic::basic_variable — Dynamic variable. [[trail_dynamic]]

=== Synopsis
[[basic_variable]]
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>

template<template< typename > class Allocator> 
class basic_variable {
public:
  // types
  typedef basic_variable< Allocator >                                            value_type;            
  typedef value_type &                                                           reference;             
  typedef const value_type &                                                     const_reference;       
  typedef unspecified                                                            difference_type;         // signed integer type 
  typedef unspecified                                                            size_type;               // unsigned integer type 
  typedef std::basic_string< char, std::char_traits< char >, Allocator >         string_type;             // std::string by default 
  typedef std::basic_string< wchar_t, std::char_traits< wchar_t >, Allocator >   wstring_type;            // std::wstring by default 
  typedef std::basic_string< char16_t, std::char_traits< char16_t >, Allocator > u16string_type;          // std::u16string by default 
  typedef std::basic_string< char32_t, std::char_traits< char32_t >, Allocator > u32string_type;          // std::u32string by default 
  typedef unspecified                                                            array_type;              // SequenceContainer. 
  typedef unspecified                                                            map_type;                // AssociativeContainer. 
  typedef unspecified                                                            pair_type;             
  typedef std::reverse_iterator< iterator >                                      reverse_iterator;      
  typedef std::reverse_iterator< const_iterator >                                const_reverse_iterator;

  // member classes/structs/unions

  class const_iterator :
    public iterator_base< const_iterator, const basic_variable::value_type >
  {
  public:
    // construct/copy/destruct
    const_iterator();
    const_iterator(const const_iterator &);
    const_iterator(const_iterator &&);
    const_iterator(const iterator &);
    explicit const_iterator(pointer, bool = true);

    // public member functions
    const_reference key() const;
    const_reference value() const;
    const_reference operator*() const;
  };

  class iterator :
    public iterator_base< iterator, basic_variable::value_type >
  {
  public:
    // construct/copy/destruct
    iterator();
    iterator(const iterator &);
    iterator(iterator &&);
    explicit iterator(const const_iterator &);
    explicit iterator(pointer, bool = true);
    explicit iterator(pointer, typename super::array_iterator);
    explicit iterator(pointer, typename super::map_iterator);
    iterator & operator=(const iterator &);
    iterator & operator=(iterator &&);

    // public member functions
    const_reference key() const;
    reference value();
    const_reference value() const;
    reference operator*();
    const_reference operator*() const;
  };

  class key_iterator :
    public iterator_base< key_iterator, const basic_variable::value_type >
  {
  public:
    // construct/copy/destruct
    key_iterator();
    key_iterator(const key_iterator &);
    key_iterator(key_iterator &&);
    explicit key_iterator(pointer, bool = true);
    key_iterator & operator=(const key_iterator &);
    key_iterator & operator=(key_iterator &&);

    // public member functions
    const_reference key() const;
    const_reference value() const;
    const_reference operator*();
    key_iterator & operator++();
  };
  template<typename T, typename  = void> 
  struct tag_traits {
  };
  template<typename T> 
  struct traits {
  };

  // construct/copy/destruct
  basic_variable();
  basic_variable(const basic_variable &);
  basic_variable(basic_variable &&) noexcept;
  template<typename T> basic_variable(T);
  basic_variable(const std::initializer_list< value_type > &);
  basic_variable(const nullable &);
  basic_variable(const char *);
  basic_variable(const wchar_t *);
  basic_variable(const char16_t *);
  basic_variable(const char32_t *);
  basic_variable(const typename basic_variable::array_type &);
  basic_variable(typename basic_variable::array_type &&);
  basic_variable(const typename basic_variable::map_type &);
  basic_variable(typename basic_variable::map_type &&);
  basic_variable & operator=(const basic_variable &);
  basic_variable & operator=(basic_variable &&);
  template<typename T> basic_variable & operator=(T);
  basic_variable & operator=(nullable);
  basic_variable & operator=(const char *);
  basic_variable & operator=(const wchar_t *);
  basic_variable & operator=(const char16_t *);
  basic_variable & operator=(const char32_t *);

  // public member functions
  basic_variable & operator+=(const basic_variable &);
  template<typename T> basic_variable & operator+=(const T &);
  basic_variable & operator+=(const char *);
  basic_variable & operator+=(const wchar_t *);
  basic_variable & operator+=(const char16_t *);
  basic_variable & operator+=(const char32_t *);
  template<typename T> T value() const;
  template<typename T> T value(std::error_code &) const noexcept;
  template<typename R> explicit operator R() const;
  template<typename R> R & assume_value();
  template<typename R> const R & assume_value() const;
  basic_variable & operator[](size_type);
  const basic_variable & operator[](size_type) const;
  basic_variable & operator[](const typename map_type::key_type &);
  const basic_variable & operator[](const typename map_type::key_type &) const;
  template<typename T> bool is() const noexcept;
  template<typename T> bool same() const noexcept;
  dynamic::code::value code() const noexcept;
  dynamic::symbol::value symbol() const noexcept;
  bool empty() const noexcept;
  size_type size() const noexcept;
  size_type max_size() const noexcept;
  void clear() noexcept;
  iterator insert(const basic_variable &);
  template<typename InputIterator> void insert(InputIterator, InputIterator);
  iterator insert(const_iterator, const basic_variable &);
  template<typename InputIterator> 
    void insert(const_iterator, InputIterator, InputIterator);
  iterator erase(const_iterator);
  iterator erase(const_iterator, const_iterator);
  void swap(basic_variable &) noexcept;
  iterator begin();
  const_iterator begin() const;
  const_iterator cbegin() const;
  iterator end();
  const_iterator end() const;
  const_iterator cend() const;
  reverse_iterator rbegin();
  const_reverse_iterator rbegin() const;
  const_reverse_iterator crbegin() const;
  reverse_iterator rend();
  const_reverse_iterator rend() const;
  const_reverse_iterator crend() const;
  key_iterator key_begin() const;
  key_iterator key_end() const;
};
----

== Description

Dynamic variable is a tagged union that can change both its type and value during program execution.

Dynamic variable is a heterogenous hierarchical data structure with a pre-determined list of supported types: fundamental data types, strings, arrays, and associative arrays.

|===
| `*Type*` | `*Tag*`
| `dynamic::nullable` | `dynamic::nullable`
| `bool` | `xref:dynamic:header-variable.adoc#boolean[dynamic::boolean]`
| `signed char` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `signed short int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `signed int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `signed long int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `signed long long int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `unsigned char` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `unsigned short int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `unsigned int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `unsigned long int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `unsigned long long int` | `xref:dynamic:header-variable.adoc#integer[dynamic::integer]`
| `float` | `xref:dynamic:header-variable.adoc#real[dynamic::real]`
| `double` | `xref:dynamic:header-variable.adoc#real[dynamic::real]`
| `long double` | `xref:dynamic:header-variable.adoc#real[dynamic::real]`
| `dynamic::string_type` | `xref:dynamic:header-variable.adoc#string[dynamic::string]`
| `dynamic::wstring_type` | `xref:dynamic:header-variable.adoc#wstring[dynamic::wstring]`
| `dynamic::u16string_type` | `xref:dynamic:header-variable.adoc#u16string[dynamic::u16string]`
| `dynamic::u32string_type` | `xref:dynamic:header-variable.adoc#u32string[dynamic::u32string]`
| `dynamic::array_type` | `dynamic::array`
| `dynamic::map_type` | `dynamic::map`
|===

== Template Parameters

1. `[.blue]#template#< [.blue]#typename# > [.blue]#class# Allocator` +
&#160;Allocator type (defaults to std::allocator)

== basic_variable public construct/copy/destruct

1. `basic_variable();` +
&#160;Constructs a default variable of type nullable. +
&#160;A default constructed variable contains null, which means it has no value. 

2. `basic_variable([.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & element);` +
&#160;Copy-constructs a copy of element. 

3. `basic_variable(xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] && element) [.blue]#noexcept#;` +
&#160;Move-constructs a copy of element. 

4. `[.blue]#template#<[.blue]##typename## T> basic_variable(T);` +
&#160;Constructs a variable of type T. +
&#160;T must be a supported type, otherwise a compilation error occurs.

5. `basic_variable([.blue]#const# std::initializer_list< xref:dynamic:header-variable.adoc[value_type] > & elements);` +
&#160;Constructs a variable from initializer list. +
&#160;If the initializer list elements contains an array of pairs then the variable will be of type map, otherwise of type array. 

6. `basic_variable([.blue]#const# nullable &);` +
&#160;Constructs a variable of type nullable. 

7. `basic_variable([.blue]#const char# *);` +
&#160;Constructs a variable of type string. 

8. `basic_variable([.blue]#const wchar_t# *);` +
&#160;Constructs a variable of type wstring. 

9. `basic_variable([.blue]#const char16_t# *);` +
&#160;Constructs a variable of type xref:dynamic:header-variable.adoc#u16string[u16string]. 

10. `basic_variable([.blue]#const char32_t# *);` +
&#160;Constructs a variable of type xref:dynamic:header-variable.adoc#u32string[u32string]. 

11. `basic_variable([.blue]#const typename# basic_variable::array_type &);` +
&#160;Construct a variable from array type. +
&#160;Re-construct a variable from the value returned by assume_value. +
&#160;Prefer to use factory or initializer-lists when creating arrays. 

12. `basic_variable([.blue]#typename# basic_variable::array_type &&);` +
&#160;Construct a variable from array type. +
&#160;Re-construct a variable from the value returned by assume_value. +
&#160;Prefer to use factory or initializer-lists when creating arrays. 

13. `basic_variable([.blue]#const typename# basic_variable::map_type &);` +
&#160;Construct a variable from map type. +
&#160;Re-construct a variable from the value returned by assume_value. +
&#160;Prefer to use factory or initializer-lists when creating associative arrays. 

14. `basic_variable([.blue]#typename# basic_variable::map_type &&);` +
&#160;Construct a variable from map type. +
&#160;Re-construct a variable from the value returned by assume_value. +
&#160;Prefer to use factory or initializer-lists when creating associative arrays. 

15. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=([.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] &);` +
&#160;Copy-asigns one variable to another. 

16. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=(xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] &&);` +
&#160;Move-assigns one variable to another. 

17. `[.blue]#template#<[.blue]##typename## T> xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=(T);` +
&#160;Assigns content to a variable. 

18. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=(nullable);` +
&#160;Assigns null to variable. 

19. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=([.blue]#const char# *);` +
&#160;Assigns a string literal to a variable. 

20. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=([.blue]#const wchar_t# *);` +
&#160;Assigns a wide-string literal to a variable. 

21. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=([.blue]#const char16_t# *);` +
&#160;Assigns a UTF-16 encoded string literal to a variable. 

22. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#=([.blue]#const char32_t# *);` +
&#160;Assigns a UTF-32 encoded string literal to a variable. 

== basic_variable public member functions

1. xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#+=([.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] &);
+
- Appends values.
- The append operator has different meanings depending on the types.

* Appending null to any other type has no effect.
* Appending any value to null overwrites the variable.
* Appending an integral value with another integral value adds the two.
* Appending a string to another string concatenates the two.
* Appending a wide string to another wide string concatenates the two.
* Appending a UTF-16 encoded string to another UTF-16 encoded string concatenates the two.
* Appending a UTF-32 encoded string to another UTF-32 encoded string concatenates the two.
* Appending an array to an array concatenates the two.
* Appending any type to an array inserts the value at the end of the array.
* Appending a map to a map merges the two.
+
|===
| `*Tag*` | `*nullable*` | `*boolean*` | `*integer*` | `*real*` | `*string*` | `*wstring*` | `xref:dynamic:header-variable.adoc#u16string[*u16string*]` | `xref:dynamic:header-variable.adoc#u32string[*u32string*]` | `*array*` | `*map*`

| `nullable` | `No&#160;effect` | `Assigns` | `Assigns` | `Assigns` | `Assigns` | `Assigns` | `Assigns` | `Assigns` | `Assigns` | `Assigns`
| `boolean` | `No effect` | `Adds` | `Adds` | `Adds` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails`
| `integer` | `No effect` | `Adds` | `Adds` | `Adds` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails`
| `real` | `No effect` | `Adds` | `Adds` | `Adds` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails`
| `string` | `No effect` | `Fails` | `Fails` | `Fails` | `Concats` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` 
| `wstring` | `No effect` | `Fails` | `Fails` | `Fails` | `Fails` | `Concats` | `Fails` | `Fails` | `Fails` | `Fails` 

| `xref:dynamic:header-variable.adoc#u16string[*u16string*]` | `No effect` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` | `Concats` | `Fails` | `Fails` | `Fails` 

| `xref:dynamic:header-variable.adoc#u32string[*u32string*]` | `No effect` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` | `Fails` | `Concats` | `Fails` | `Fails`
| `array` | `No effect` | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts` | `Concats` | `Inserts`
| `map` | `No effect` | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Inserts`  | `Merges`
|===

2. `[.blue]#template#<[.blue]##typename## T> xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#+=([.blue]#const# T &);` +
&#160;This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

3. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#+=([.blue]#const char# *);` +
&#160;This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

4. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#+=([.blue]#const wchar_t# *);` +
&#160;This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

5. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#+=([.blue]#const char16_t# *);` +
&#160;This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

6. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#+=([.blue]#const char32_t# *);` +
&#160;This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

7. `[.blue]#template#<[.blue]##typename## T> T value() [.blue]#const#;` +
Returns current value as type T. +
Calls xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable]<Allocator>::value<T>(std::error_code&) and throws an exception if an error occurred. +
*See Also:* +
basic_variable<Allocator>::value<T>(std::error_code&)
+
[%autowidth, frame=none, grid=none]
|===
| *Template Parameters:* | *T* {space} Supported type
| *Throws:* |  `xref:dynamic:header-error.adoc[dynamic::error]` with `dynamic::incompatible_type` if T is an unsupported or incompatible type.
|===



8. `[.blue]#template#<[.blue]##typename## T> T value(std::error_code & error) [.blue]#const noexcept#;` +
Returns current value as type T. +
T can either be a type or a tag. +
If current tag is `xref:dynamic:header-variable.adoc#integer[dynamic::integer]` or `xref:dynamic:header-variable.adoc#real[dynamic::real]`, then T can be any arithmetic type. Such a conversion may result in loss of precision. +
If current tag is any other type, then T must be the associated type. +
If T is a tag, then the following types are used.
+
|===
| `*tags*` | `*Type*`
| `nullable` | `dynamic::nullable`
| `boolean` | `bool`
| `integer` | `int`
| `real` | `float`
| `string` | `variable::string_type`
| `wstring` | `variable::wstring_type`
| `xref:dynamic:header-variable.adoc#u16string[u16string]` | `variable::u16string_type`
| `xref:dynamic:header-variable.adoc#u32string[u32string]` | `variable::u32string_type`
| `array` | `variable::array_type`
| `map` | `variable::map_type`
|===
+
[%autowidth, frame=none, grid=none]
|===
| *Parameters:* | {space} *error* {space} Set to `dynamic::incompatible_type` if T is an unsupported or incompatible type, otherwise unchanged.
| *Template Parameters:* | {space}  *T* {space}{space} &#160;Supported type
|===




9. `[.blue]#template#<[.blue]##typename## R> [.blue]#explicit operator# R() [.blue]#const#;` +
Returns current value as type R. +
Calls xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable]<Allocator>::value<R>() +
*See Also:* +
basic_variable<Allocator>::value<T>() 

10. `[.blue]#template#<[.blue]##typename## R> R & assume_value();` +
Returns reference to stored value. +
assume_value() has a narrow contract. Using a type R that does not match the type of the stored value results in undefined behavior.
+
[%autowidth, frame=none, grid=none]
|===
| *Template Parameters:* | {space} *R* {space} Supported type.
| *Requires:* | {space} basic_variable<Allocator>::same<R>() is true. 
|===


11. `[.blue]#template#<[.blue]##typename## R> [.blue]#const# R & assume_value() [.blue]#const#;` +
Returns constant reference to stored value. +
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

12. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#[](size_type position);` +
Returns reference to element at specified position. +
The stored value must be an array. +
No bounds-checking is performed.
+
[%autowidth, frame=none, grid=none]
|===
| *Parameters:* | {space} *position* {space} Index position.
| *Requires:* |  {space} basic_variable<Allocator>::is<array>() is true
|===


13. `[.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#[](size_type position) [.blue]#const#;` +
Returns constant reference to element at specified position. +
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.

14. `xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & [.blue]#operator#[]([.blue]#const typename# map_type::key_type & key);` +
Returns reference to element indexed by key. +
Returns a reference to the value associated with key in an associative array, or inserts a key of none exists. +
If the current tag is nullable, then the current value is changed into an associative array and key is inserted. +
+
[%autowidth, frame=none, grid=none]
|===
| *Requires:* | {space} basic_variable<Allocator>::is<map>() is true.
| *Throws:* |  {space} xref:dynamic:header-error#class_error[dynamic::error] with dynamic::incompatible_type is thrown if current tag is not `dynamic::map`.
|===


15. `[.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] &`
`[.blue]#operator#[]([.blue]#const typename# map_type::key_type & key) [.blue]#const#;`
Returns constant reference to element indexed by key. +
Returns a reference to the value associated with key in an associative array.
+
[%autowidth, frame=none, grid=none]
|===
| *Requires:* | {space} `basic_variable<Allocator>::is<map>() is true.` +
| *Throws:* |  {space} xref:dynamic:header-error#class_error[dynamic::error] with dynamic::incompatible_type is thrown if key does not exist in associative array. +
{space} with dynamic::incompatible_type is thrown if current tag is not `dynamic::map.`
|===


16. `[.blue]#template#<[.blue]##typename## T> [.blue]#bool# is() [.blue]#const noexcept#;` [[is_T]]
Checks if variable has a given tag. +
Converts T into a tag, and returns true if variable has the same tag, otherwise returns false. +
If T is a tag, then this tag is used directly: variable v = true; // Boolean assert(v.is<boolean>()); +
If T is a C++ type, then this is converted a tag: variable v = true; // Boolean assert(v.is<bool>()); // Same as is<boolean>() +
The type-to-tag conversion means that any type from the same category can be used: variable v = 2; // Integer assert(v.is<int>()); // Same as is<integer>() assert(v.is<long int>()); // Same as is<integer>() +
Checking for an array or a map can either be done by a tag: variable v = { 1, 2, 3}; // Array assert(v.is<array>()); +
or by the unspecified variable::array_type or variable::map_type type aliases: variable v = { 1, 2, 3}; // Array assert(v.is<variable::array_type>()); +
Using unsupported types will result in a compilation error. + 
+
[%autowidth, frame=none, grid=none]
|===
| *Template Parameters:* | {space} *T* {space} Type or tag to be checked.
|===

17. `[.blue]#template#<[.blue]##typename## T> [.blue]#bool# same() [.blue]#const noexcept#;` + [[same_T]]
Checks if variable has exactly a given type. +
Returns true if variable has the exact same type as T, otherwise returns false. variable v = int(2); // int assert(v.same<int>() == true); // Same as int assert(v.same<long int>() == false); // Not same as long int +
+
[%autowidth, frame=none, grid=none]
|===
| *Template Parameters:* | {space} *T* {space} Type to be checked.
|===


18. `dynamic::code::value code() [.blue]#const noexcept#;` + [[d_code]]
Returns the current code. +
Code is an enumerator that represents the exact type that is currently stored.
+
|====
| `*Type*` | `*Code*`
| `dynamic::nullable` | `dynamic::code::null`
| `bool` | `dynamic::code::boolean`
| `signed char` | `dynamic::code::signed_char`
| `signed short int` | `dynamic::code::signed_short_integer`
| `signed int` | `dynamic::code::signed_integer`
| `signed long int` | `dynamic::code::signed_long_integer`
| `signed long long int` | `dynamic::code::signed_long_long_integer`
| `unsigned char` | `dynamic::code::unsigned_char`
| `unsigned short int` | `dynamic::code::unsigned_short_integer`
| `unsigned int` | `dynamic::code::unsigned_integer`
| `unsigned long int` | `dynamic::code::unsigned_long_integer`
| `unsigned long long int` | `dynamic::code::unsigned_long_long_integer`
| `float` | `dynamic::code::real`
| `double` | `dynamic::code::long_real`
| `long double` | `dynamic::code::long_long_real`
| `dynamic::string_type` | `dynamic::code::string`
| `dynamic::wstring_type` | `dynamic::code::wstring`
| `dynamic::u16string_type` | `dynamic::code::u16string`
| `dynamic::u32string_type` | `dynamic::code::u32string`
| `dynamic::array_type` | `dynamic::code::array`
| `dynamic::map_type` | `dynamic::code::map`
|====


19. `dynamic::symbol::value symbol() [.blue]#const noexcept#;` + [[d_symbol]]
Returns the current symbol. +
Symbol is an enumerator that represents the tag of the type currently stored.
+
|====
| `*Type*` | `*Tag*` | `*Symbol*` 
| `dynamic::nullable` | `nullable` | `dynamic::symbol::null` 
| `bool` | `boolean` | `dynamic::symbol::boolean` 
| `signed char` | `integer` | `dynamic::symbol::integer` 
| `signed short int` | `integer` | `dynamic::symbol::integer` 
| `signed int` | `integer` | `dynamic::symbol::integer` 
| `signed long int` | `integer` | `dynamic::symbol::integer` 
| `signed long long int` | `integer` | `dynamic::symbol::integer` 
| `unsigned char` | `integer` | `dynamic::symbol::integer` 
| `unsigned short int` | `integer` | `dynamic::symbol::integer` 
| `unsigned int` | `integer` | `dynamic::symbol::integer` 
| `unsigned long int` | `integer` | `dynamic::symbol::integer` 
| `unsigned long long int` | `integer` | `dynamic::symbol::integer` 
| `float` | `real` | `dynamic::symbol::real` 
| `double` | `real` | `dynamic::symbol::real` 
| `long double` | `real` | `dynamic::symbol::real` 
| `dynamic::string_type` | `string` | `dynamic::symbol::string` 
| `dynamic::wstring_type` | `wstring` | `dynamic::symbol::wstring` 
| `dynamic::u16string_type` | `xref:dynamic:header-variable#u16string[u16string]` | `dynamic::symbol::u16string` 
| `dynamic::u32string_type` | `xref:dynamic:header-variable#u32string[u32string]` | `dynamic::symbol::u32string` 
| `dynamic::array_type` | `array` | `dynamic::symbol::array` 
| `dynamic::map_type` | `map` | `dynamic::symbol::map` 
|====


20. `[.blue]#bool# empty() [.blue]#const noexcept#;` +
Checks if variable is empty. +
Same as size() == 0

21. `size_type size() [.blue]#const noexcept#;` +
Returns the number of elements in variable. +
The number of elements stored in a variable corresponds to the iteration count, that is v.size() == std::distance(v.begin(), v.end()). +
Notice that strings are regarded as single elements, rather than a sequence of characters.
+
|====
| `*Current tag*` | `*Size*` | `*Description*`
| `nullable` | `0` | `null is an empty variable.` 
| `boolean` | `1` | `boolean is a single element.` 
| `integer` | `1` | `integer is a single element.` 
| `real` | `1` | `real is a single element.` 
| `string` | `1` | `string is a single element, so variable::string_type::size() is not used.` 
| `wstring` | `1` | `wstring is a single element, so variable::wstring_type::size() is not used.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `1` | `xref:dynamic:header-variable#u16string[u16string] is a single element, so variable::u16string_type::size() is not used.` 

| `xref:dynamic:header-variable#u32string[u32string]` | `1` | `xref:dynamic:header-variable#u32string[u32string] is a single element, so variable::u32string_type::size() is not used.` 

| `array` | `variable::array_type::size()` | `The number of elements in the array. ` 
| `map` | `variable::map_type::size()` | `The number of elements (pairs) in the map.` 
|====

22. `size_type max_size() [.blue]#const noexcept#;` +
Returns the maximum possible number of elements.
+
|====
| `*Current tag*` | `*Size*` | `*Description*`
| `nullable` | `0` | `null cannot contain element.` 
| `boolean` | `1` | `Can contain a single boolean element.` 
| `integer` | `1` | `Can contain a single integer element.` 
| `real` | `1` | `Can contain a single real element.` 
| `string` | `1` | `Can contain a single string element, so variable::string_type::max_size() is not used.` 
| `wstring` | `1` | `Can contain a single wstring element, so variable::wstring_type::max_size() is not used.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `1` | `Can contain a single xref:dynamic:header-variable#u16string[u16string] element, so variable::u16string_type::max_size() is not used.` 

| `xref:dynamic:header-variable#u16string[u32string]` | `1` | `Can contain a single xref:dynamic:header-variable#u32string[u32string] element, so variable::u32string_type::max_size() is not used.` 

| `array` | `variable::array_type::max_size()` | `The maximum possible number of elements in the array.` 
| `map` | `variable::map_type::max_size()` | `The maximum possible number of elements (pairs) in the map.` 
|==== 

23. `[.blue]#void# clear() [.blue]#noexcept#;` +
Clears the content of the variable. +
Only the value is cleared. The type is not modified.
+
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `No effect.` 
| `boolean` | `Sets the default constructed value.` 
| `integer` | `Sets the default constructed value.` 
| `real` | `Sets the default constructed value. ` 
| `string` | `Calls variable::string_type::clear().` 
| `wstring` | `Calls variable::wstring_type::clear().` 
| `xref:dynamic:header-variable#u16string[u16string]` | `Calls variable::u16string_type::clear().` 
| `xref:dynamic:header-variable#u32string[u32string]` | `Calls variable::u32string_type::clear().` 
| `array` | `Calls variable::array_type::clear().` 
| `map` | `Calls variable::map_type::clear().` 
|====

24. `xref:dynamic:header-variable#class_iterator[iterator] insert([.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & element);` +
Inserts element into variable. 
+
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `Create array and insert element.` 
| `boolean` | `Fails.` 
| `integer` | `Fails.` 
| `real` | `Fails.` 
| `string` | `Fails.` 
| `wstring` | `Fails.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `Fails.` 
| `xref:dynamic:header-variable#u32string[u32string]` | `Fails.` 
| `array` | `Insert element at end.` 
| `map` | `Insert element, otherwise fails if element is not pair.` 
|====

25. `[.blue]#template#<[.blue]##typename## InputIterator>` +
[.blue]#void# insert(InputIterator begin, InputIterator end); +
+
Inserts range into variable. 
+
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `Create array and insert range.` 
| `boolean` | `Fails.` 
| `integer` | `Fails.` 
| `real` | `Fails.` 
| `string` | `Fails.` 
| `wstring` | `Fails.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `Fails.` 
| `xref:dynamic:header-variable#u32string[u32string]` | `Fails.` 
| `array` | `Insert range at end.` 
| `map` | `Insert range, otherwise fails if any element in range is not pair.` 
|====

26. `xref:dynamic:header-variable#class_iterator[iterator] insert(xref:dynamic:header-variable#const_iterator[const_iterator] position, [.blue]#const# xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & element);` +
&#160;Inserts element into variable.
+
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `Fails.` 
| `boolean` | `Fails.` 
| `integer` | `Fails.` 
| `real` | `Fails.` 
| `string` | `Fails.` 
| `wstring` | `Fails.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `Fails.` 
| `xref:dynamic:header-variable#u32string[u32string]` | `Fails.` 
| `array` | `Insert element before position.` 
| `map` | `Insert element with position as hint, otherwise fails if element is not pair.` 
|====

27. `[.blue]#template#<[.blue]##typename## InputIterator>` +
&#160; [.blue]#void# insert(xref:dynamic:header-variable#const_iterator[const_iterator], InputIterator begin, InputIterator end);
Inserts range into variable.
+
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `Fails.` 
| `boolean` | `Fails.` 
| `integer` | `Fails.` 
| `real` | `Fails.` 
| `string` | `Fails.` 
| `wstring` | `Fails.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `Fails.` 
| `xref:dynamic:header-variable#u32string[u32string]` | `Fails.` 
| `array` | `Insert range before position.` 
| `map` | `Insert range with position as hint, otherwise fails if any element in range is not pair.` 
|====

28. xref:dynamic:header-variable#class_iterator[iterator] erase(xref:dynamic:header-variable#const_iterator[const_iterator] position); +
Erases an element from variable. + 
Returns iterator following last erased element.
+ 
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `No effect.` 
| `boolean` | `No effect.` 
| `integer` | `No effect.` 
| `real` | `No effect.` 
| `string` | `No effect.` 
| `wstring` | `No effect.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `No effect.` 
| `xref:dynamic:header-variable#u32string[u32string]` | `No effect.` 
| `array` | `Erases element at position.` 
| `map` | `Erases element at position.` 
|====

29. xref:dynamic:header-variable#class_iterator[iterator] erase(xref:dynamic:header-variable#const_iterator[const_iterator] begin, xref:dynamic:header-variable#const_iterator[const_iterator] end); +
Erases range from variable. +
Returns iterator following last erased element. 
+
|====
| `*Current tag*` | `*Behavior*`
| `nullable` | `No effect.` 
| `boolean` | `No effect.` 
| `integer` | `No effect.` 
| `real` | `No effect.` 
| `string` | `No effect.` 
| `wstring` | `No effect.` 
| `xref:dynamic:header-variable#u16string[u16string]` | `No effect.` 
| `xref:dynamic:header-variable#u32string[u32string]` | `No effect`
| `array` | `Erases elements in range.` 
| `map` | `Erases elements in range.` 
|====

30. `[.blue]#void# swap(xref:dynamic:header-variable.adoc#trail_dynamic[basic_variable] & other) [.blue]#noexcept#;` +
Exchange contents of variable and other. 

31. xref:dynamic:header-variable#class_iterator[iterator] begin(); +
Returns an iterator to the beginning. 

32. xref:dynamic:header-variable#const_iterator[const_iterator] begin() [.blue]#const#; +
Returns an iterator to the beginning. 

33. xref:dynamic:header-variable#const_iterator[const_iterator] cbegin() [.blue]#const#; +
Returns an iterator to the beginning.

34. xref:dynamic:header-variable#class_iterator[iterator] end(); +
Returns an iterator to the end. 

35. xref:dynamic:header-variable#const_iterator[const_iterator] end() [.blue]#const#; +
Returns an iterator to the end. 

36. xref:dynamic:header-variable#const_iterator[const_iterator] cend() [.blue]#const#; +
Returns an iterator to the end. 

37. reverse_iterator rbegin(); +
Returns a reverse iterator to the beginning. 

38. const_reverse_iterator rbegin() [.blue]#const#; +
Returns a reverse iterator to the beginning.

39. const_reverse_iterator crbegin() [.blue]#const#; +
Returns a reverse iterator to the beginning.

40. reverse_iterator rend(); +
Returns a reverse iterator to the end. 

41. const_reverse_iterator rend() [.blue]#const#; +
Returns a reverse iterator to the end. 

42. const_reverse_iterator crend() [.blue]#const#; +
Returns a reverse iterator to the end. 

43. xref:dynamic:header-variable#key_iterator[key_iterator] key_begin() [.blue]#const#; +
Returns a key iterator to the beginning. 

44. xref:dynamic:header-variable#key_iterator[key_iterator] key_end() [.blue]#const;# +
Returns a key iterator to the end. 

[[const_iterator]]
== Class const_iterator

trial::dynamic::basic_variable::const_iterator

=== Synopsis

[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>



class const_iterator :
  public iterator_base< const_iterator, const basic_variable::value_type >
{
public:
  // construct/copy/destruct
  const_iterator();
  const_iterator(const const_iterator &);
  const_iterator(const_iterator &&);
  const_iterator(const iterator &);
  explicit const_iterator(pointer, bool = true);

  // public member functions
  const_reference key() const;
  const_reference value() const;
  const_reference operator*() const;
};
----


== Description

=== const_iterator public construct/copy/destruct
. const_iterator();
. const_iterator([.blue]#const# xref:dynamic:header-variable#const_iterator[const_iterator] & other);
. const_iterator(xref:dynamic:header-variable#const_iterator[const_iterator] && other);
. const_iterator([.blue]#const# xref:dynamic:header-variable#iterator[iterator] & other);
. [.blue]#explicit# const_iterator(pointer p, [.blue]#bool# initialize = [.blue]#true#);

=== const_iterator public member functions

. xref:dynamic:header-variable#trail_dynamic[const_reference] key() [.blue]#const#;
. xref:dynamic:header-variable#trail_dynamic[const_reference] value() [.blue]#const#;
. xref:dynamic:header-variable#trail_dynamic[const_reference] [.blue]#operator#*() [.blue]#const#;

[[class_iterator]]
== Class iterator

trial::dynamic::basic_variable::iterator

=== Synopsis

[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>



class iterator : public iterator_base< iterator, basic_variable::value_type > {
public:
  // construct/copy/destruct
  iterator();
  iterator(const iterator &);
  iterator(iterator &&);
  explicit iterator(const const_iterator &);
  explicit iterator(pointer, bool = true);
  explicit iterator(pointer, typename super::array_iterator);
  explicit iterator(pointer, typename super::map_iterator);
  iterator & operator=(const iterator &);
  iterator & operator=(iterator &&);

  // public member functions
  const_reference key() const;
  reference value();
  const_reference value() const;
  reference operator*();
  const_reference operator*() const;
};
----

== Description

=== iterator public construct/copy/destruct
. iterator();
. iterator([.blue]#const# xref:dynamic:header-variable#iterator[iterator] & other);
. iterator(xref:dynamic:header-variable#iterator[iterator] && other);
. [.blue]#explicit# iterator([.blue]#const# xref:dynamic:header-variable#const_iterator[const_iterator] & other);
. [.blue]#explicit# iterator(pointer p, [.blue]#bool# initialize = [.blue]#true#);
. [.blue]#explicit# iterator(pointer p, [.blue]#typename# super::array_iterator);
. [.blue]#explicit# iterator(pointer p, [.blue]#typename# super::map_iterator);
. xref:dynamic:header-variable#iterator[iterator] & [.blue]#operator#=([.blue]#const# xref:dynamic:header-variable#iterator[iterator] & other);
. xref:dynamic:header-variable#iterator[iterator] & [.blue]#operator#=(xref:dynamic:header-variable#iterator[iterator] && other);

=== iterator public member functions
. xref:dynamic:header-variable#trail_dynamic[const_reference] key() [.blue]#const#;
. xref:dynamic:header-variable#trail_dynamic[reference] value();
. xref:dynamic:header-variable#trail_dynamic[const_reference] value() [.blue]#const#;
. xref:dynamic:header-variable#trail_dynamic[reference] [.blue]#operator#*();
. xref:dynamic:header-variable#trail_dynamic[const_reference] [.blue]#operator#*() [.blue]#const#;

[[key_iterator]]
== Class key_iterator

trial::dynamic::basic_variable::key_iterator

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>



class key_iterator :
  public iterator_base< key_iterator, const basic_variable::value_type >
{
public:
  // construct/copy/destruct
  key_iterator();
  key_iterator(const key_iterator &);
  key_iterator(key_iterator &&);
  explicit key_iterator(pointer, bool = true);
  key_iterator & operator=(const key_iterator &);
  key_iterator & operator=(key_iterator &&);

  // public member functions
  const_reference key() const;
  const_reference value() const;
  const_reference operator*();
  key_iterator & operator++();
};
----

== Description

=== key_iterator public construct/copy/destruct

. key_iterator();
. key_iterator([.blue]#const# xref:dynamic:header-variable#key_iterator[key_iterator] & other);
. key_iterator(xref:dynamic:header-variable#key_iterator[key_iterator] && other);
. [.blue]#explicit# key_iterator(pointer p, [.blue]#bool# initialize = [.blue]#true#);
. xref:dynamic:header-variable#key_iterator[key_iterator] & [.blue]#operator#=([.blue]#const# xref:dynamic:header-variable#key_iterator[key_iterator] & other);
. xref:dynamic:header-variable#key_iterator[key_iterator] & [.blue]#operator#=(xref:dynamic:header-variable#key_iterator[key_iterator] && other);

=== key_iterator public member functions

. xref:dynamic:header-variable#trail_dynamic[const_reference] key() [.blue]#const#;
. xref:dynamic:header-variable#trail_dynamic[const_reference] value() [.blue]#const#;
. xref:dynamic:header-variable#trail_dynamic[const_reference] [.blue]#operator#*();
. xref:dynamic:header-variable#key_iterator[key_iterator] & [.blue]#operator#++();


== Struct template tag_traits

trial::dynamic::basic_variable::tag_traits

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


template<typename T, typename  = void> 
struct tag_traits {
};
----


== Struct template traits

trial::dynamic::basic_variable::traits

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


template<typename T> 
struct traits {
};
----

[[boolean]]
== Struct boolean

trial::dynamic::boolean

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct boolean {
};
----

[[integer]]
== Struct integer

trial::dynamic::integer

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct integer {
};
----

[[real]]
== Struct real

trial::dynamic::real

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct real {
};
----

[[string]]
== Struct string

trial::dynamic::string

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct string {
};
----

[[u16string]]
== Struct u16string

trial::dynamic::u16string

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct u16string {
};
----

[[u32string]]
== Struct u32string

trial::dynamic::u32string

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct u32string {
};
----
[[wstring]]
== Struct wstring

trial::dynamic::wstring

=== Synopsis
[source,cpp]
----
// In header: <boost/libs/trial.protocol/include/trial/dynamic/variable.hpp>


struct wstring {
};
----
