///////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2017 Bjorn Reese <breese@users.sourceforge.net>
//
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
//
///////////////////////////////////////////////////////////////////////////////

:doctype: book
:toc: left
:toclevels: 2
:source-highlighter: pygments

= Trial.Dynamic
Bjørn Reese

== Overview

Trial.Dynamic is a pass:[C++11] header-only library with a pass:[C++] dynamic
variable similar to the Javascript dynamic variable.

* `dynamic::variable` is a https://en.wikipedia.org/wiki/Tagged_union[tagged union]
  whose type and value can change dynamically during program execution.

* `dynamic::variable` supports http://en.cppreference.com/w/cpp/language/types[fundamental data types]footnote:[Sign-less
  characters (`char`, `wchar_t`, `char16_t`, and `char32_t`) are not supported
  directly, but only indirectly via strings.]footnote:[`void` is not a
  http://stepanovpapers.com/DeSt98.pdf[regular type],
  so it has been replaced with the `dynamic::nullable` type and the
  `dynamic::null` value.] and strings.

* `dynamic::variable` supports arrays and associative arrays and can therefore
  act as a heterogenous tree data structure.

* `dynamic::variable` meets the requirements of http://en.cppreference.com/w/cpp/concept/Container[Container]
  and therefore works with standard pass:[C++] algorithms.

The resemblance between `dynamic::variable` and http://en.cppreference.com/w/cpp/utility/variant[`std::variant`]
is obvious, but there are also notable differences. While `std::variant` supports
custom types, `dynamic::variable` is restricted to the above-mentioned data types
and containers. This restriction enables `dynamic::variable` to adhere to the
Container concept, and thus to have a richer interface that works with algorithms.

`dynamic::variable` is intended for tasks like handling configuration data, parse
tree for network protocols, and protocol serialization.

== Introduction by Example

All examples throughout this documentation assumes the following prologue:

[source,cpp]
----
#include <trial/dynamic/variable.hpp>
namespace dynamic = trial::dynamic;
----

A http://en.cppreference.com/w/cpp/language/default_initialization[default-initialized]
`dynamic::variable` has no value. No value is represented as the `dynamic::nullable`
type.
[source]
----
// Create an empty variable
dynamic::variable data;
assert(data.is<dynamic::nullable>());
assert(data == dynamic::null);
----
We can morph the above variable into a boolean type simply by assigning a boolean
value to it.
[source,cpp]
----
// Change into boolean
data = true;
assert(data.is<bool>());
assert(data == true);
----
We can even morph it into an array by assigning an
http://en.cppreference.com/w/cpp/utility/initializer_list[initializer list] to it.
[source,cpp]
----
// Change into array
data = { 1, 20, 300 };
assert(data.is<dynamic::array>());
assert(data.size() == 3);
assert(data[0] == 1);
assert(data[1] == 20);
assert(data[2] == 300);
----
Now that the variable contains an array of integers, it makes sense to calculate
its sum.
[source]
----
#include <numeric>

// Calculate sum
auto sum = std::accumulate(data.begin(), data.end(), dynamic::variable());
assert(sum == 1 + 20 + 300);
----
Finally we morph our variable into an associative array.
[source,cpp]
----

// Change into associative array
data =
  {
    { "alpha", null },             // nullable
    { "bravo", true },             // boolean
    { "charlie", 2 },              // integer
    { "delta", 3.0 },              // floating-point number
    { "echo", "blue" },            // string
    { "foxtrot", { 1, 2, 3 } },    // nested array of integers
    { "golf", { { "level", 2 } } } // nested associative array
  };
assert(data.is<dynamic::map>());
assert(data.size() == 7);

----
